---
deployment:
  tasks:
    - export NODE_ENV=production
    - /opt/cpanel/ea-nodejs18/bin/npm install
    - /opt/cpanel/ea-nodejs18/bin/pm2 restart app.js || /opt/cpanel/ea-nodejs18/bin/pm2 start app.js
